version: "3.7"

services:
  app_proxy:
   environment:
     APP_HOST: pinserver_web_1
     APP_PORT: 8081

  node:
    image: tulipan81/blind_pin_server:v0.0.1@sha256:1d87942f43cf182bf94f4789e9177a9644588fd20cf134d52377f4e1042d3932
    depends_on:
      - tor
      - web
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - $APP_PINSERVER_PORT:$APP_PINSERVER_PORT
    volumes:
      - ${APP_DATA_DIR}/generate.py:/generate.py
      - ${APP_DATA_DIR}/data/server_private_key.key:/server_private_key.key
      - ${APP_DATA_DIR}/data/pins:/pins

  web: 
    image: tulipan81/pinserver_web:v0.0.1@sha256:06795d95728ef1183e81ea11c6f3b0d4708f1d1dd40162ba6fd8c25ee6fb2941
    depends_on: 
      - tor
    restart: on-failure
    ports:
      - $APP_PINSERVER_WEB_PORT:$APP_PINSERVER_WEB_PORT
    environment:
      PINSERVER_URL: ${APP_PINSERVER_HIDDEN_SERVICE}
      PINSERVER_PORT: ${APP_PINSERVER_PORT}
  
  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"