version: "3.7"

services:
  app_proxy:
   environment:
     APP_HOST: pinserver_web_1
     APP_PORT: $APP_PINSERVER_WEB_PORT

  node:
    image: tulipan81/blind_pin_server:v0.0.2@sha256:c3d32ac20594af9303de1971d014f39929a76efd4aa9717bedb77814117e1f98
    depends_on:
      - tor
      - web
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - $APP_PINSERVER_PORT:$APP_PINSERVER_PORT
    volumes:
      - ${APP_DATA_DIR}/data/server_public_key.pub:/server_public_key.pub
      - ${APP_DATA_DIR}/data/server_private_key.key:/server_private_key.key
      - ${APP_DATA_DIR}/data/pins:/pins

  web: 
    image: tulipan81/pinserver_web:v0.0.15@sha256:4cba37193f918e8fc91a124a222e05ca35630a31094ded18139d4bab128275b8
    depends_on: 
      - tor
    restart: on-failure
    ports:
      - $APP_PINSERVER_WEB_PORT:$APP_PINSERVER_WEB_PORT
    volumes:
      - ${APP_DATA_DIR}/data/server_public_key.pub:/app/server_public_key.pub
      - ${APP_DATA_DIR}/data/server_private_key.key:/app/server_private_key.key
      - ${APP_DATA_DIR}/data/pins:/app/pins
    environment:
      PINSERVER_URL: ${APP_PINSERVER_HIDDEN_SERVICE}
      PINSERVER_PORT: ${APP_PINSERVER_PORT}
  
  tor:
    image: getumbrel/tor:0.4.7.8@sha256:2ace83f22501f58857fa9b403009f595137fa2e7986c4fda79d82a8119072b6a
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/torrc:/etc/tor/torrc:ro
      - ${TOR_DATA_DIR}:/data
    environment:
      HOME: "/tmp"